sudo: required

language: scala

scala:
  - 2.12.4

jdk:
  - oraclejdk8

services:
  - docker

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
  - $HOME/.ivy2/cache/
  - $HOME/.sbt/boot/
  - ./node_modules/

before_install:
  - npm install
  - npm install -g gulp

script:
  - sbt compile
  - sbt test

after_success:
  - sbt publish
  - ./travis/publish.sh
